teams/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('teams.views',
    url(
        regex = r'^(?P<format>(xml))?/?$',
        view = 'teams',
        name = 'teams'),
    url(
        regex = r'^(?P<team_slug>[\w\-@]+)/$',
        view = 'team',
        name = 'team_slug'),
    url(
        regex = r'^(?P<team_slug>[\w\-@]+)/edit/',
        view = 'team_edit',
        name = 'team_edit'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(
        regex = r'^$',
        view = 'common.views.index',
        name = 'home'),
    url(
        regex = r'^login/$',
        view = 'common.views.site_login',
        name = 'login'),
    url(
        regex = r'^register/$',
        view = 'common.views.site_register',
        name = 'register'),
    url(
        regex = r'^help/(?P<topic>\w+)/$',
        view = 'common.views.help',
        name = 'help'),
    url(
        regex = r'^register/success$',
        view = TemplateView.as_view(template_name="registration/register_success.html"),
        name = 'register_success'),
    url(
        regex = r'^register/activate/(?P<key>\w+)$',
        view = 'common.views.activate_account',
        name = 'register_activation'),
    url(
        regex = r'^password_reset/$',
        view = 'django.contrib.auth.views.password_reset',
        kwargs = {'template_name':'registration/password_reset_form.html'}),
    url(
        regex = r'^password_reset/done/$',
        view = 'django.contrib.auth.views.password_reset_done',
        kwargs = {'template_name':'registration/password_reset_done.html'}),
    url(
        regex = r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        view = 'django.contrib.auth.views.password_reset_confirm'),
    url(
        regex = r'^reset/done/$',
        view = 'django.contrib.auth.views.password_reset_complete'),
    url(r'^teams/', include('teams.urls')),
    url(r'^people/', include('people.urls')),
    url(# users is the hardcoded url in the contrib.auth User class, making it identical to /people
        r'^users/', include('people.urls')),
    url(r'^languages/', include('languages.urls')),
    url(r'^vertimus/', include('vertimus.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rss/', include('feeds.urls')),
)

urlpatterns += patterns('stats.views',
    url(
        regex = r'^module/(?P<format>(html|json|xml))?/?$',
        view = 'modules',
        name = 'modules'),
    url(
        regex = r'^module/po/(?P<module_name>[\w\-\+]+)/(?P<domain>[\w~\-]+)/(?P<branch_name>[\w\-\.]+)/(?P<filename>.*)$',
        view = 'dynamic_po',
        name = 'dynamic_po'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/$',
        view = 'module'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/edit/branches/$',
        view = 'module_edit_branches'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/branch/(?P<branch_name>[\w\-\.]+)/$',
        view = 'module_branch'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/(?P<potbase>[\w~-]+)/(?P<branch_name>[\w\-\.]+)/(?P<langcode>[\w@]+)/images/$',
        view = 'docimages'),
    url(
        regex = r'^releases/(?P<format>(html|json|xml))?/?$',
        view = 'releases',
        name = 'releases'),
    url(
        regex = r'^releases/(?P<release_name>[\w-]+)/(?P<format>(html|xml))?/?$',
        view = 'release'),
    url(
        regex = r'^releases/compare/(?P<dtype>\w+)/(?P<rels_to_compare>[/\w-]+)/$',
        view = 'compare_by_releases'),
)

if 'django_openid_auth' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^openid/', include('django_openid_auth.urls')),
    )

if settings.STATIC_SERVE:
    urlpatterns += patterns('',
        url(
            regex = r'^media/(?P<path>.*)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.MEDIA_ROOT}),
        url(
            regex = r'^POT/(?P<path>.*)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.POTDIR}),
        url(
            regex = r'^(robots.txt)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.MEDIA_ROOT})
    )

teams/models.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2008 Stéphane Raimbault <stephane.raimbault@gmail.com>.
# Copyright (c) 2009 Claude Paroz <claude@2xlibre.net>
#
# This file is part of Damned Lies.
#
# Damned Lies is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Damned Lies is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Damned Lies; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

from datetime import datetime, timedelta

from django.db import models
from django.core import mail
from django.utils import translation
from django.utils.translation import ugettext_lazy, ugettext as _
from django.conf import settings
from django.contrib.sites.models import Site
from people.models import Person

class TeamManager(models.Manager):

    def all_with_coordinator(self):
        """
        Returns all teams with the coordinator already prefilled. Use that
        function to reduce the size of extracted data and the numbers of objects
        built or use all_with_roles() if you need informations about the other
        roles.
        """
        teams = self.all()
        roles = Role.objects.select_related("person").filter(role='coordinator',
                                                                is_active=True)
        role_dict = {}

        for role in roles:
            # Only one coordinator by team
            role_dict[role.team_id] = role

        for team in teams:
            try:
                role = role_dict[team.id]
                team.roles = {'coordinator': [role.person]}
            except KeyError:
                # Abnormal because a team must have a coordinator but of no
                # consequence
                pass
        return teams

    def all_with_roles(self):
        """
        This method prefills team.coordinator/committer/reviewer/translator to
        reduce subsequent database access.
        """
        teams = self.all()
        roles = Role.objects.select_related("person").filter(is_active=True)
        role_dict = {}

        for role in roles:
            if role.team_id not in role_dict:
                role_dict[role.team_id] = [role]
            else:
                role_dict[role.team_id].append(role)

        for team in teams:
            try:
                for role in role_dict[team.id]:
                    team.fill_role(role.role, role.person)
            except KeyError:
                # Abnormal because a team must have a coordinator but of no
                # consequence
                pass
        return teams


class Team(models.Model):
    """The lang_code is generally used for the name of the team."""

    name = models.CharField(max_length=80)
    description = models.TextField()
    use_workflow = models.BooleanField(default=True)
    presentation = models.TextField(blank=True, verbose_name=_("Presentation"))
    members = models.ManyToManyField(Person, through='Role', related_name='teams')
    webpage_url = models.URLField(null=True, blank=True, verbose_name=_("Web page"))
    mailing_list = models.EmailField(null=True, blank=True, verbose_name=_("Mailing list"))
    mailing_list_subscribe = models.URLField(null=True, blank=True, verbose_name=_("URL to subscribe"))
    objects = TeamManager()

    class Meta:
        db_table = 'team'
        ordering = ('description',)

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self.roles = None

    def __unicode__(self):
        return self.description

    @models.permalink
    def get_absolute_url(self):
        return ('team_slug', [self.name])

    def can_edit(self, user):
        """ Return True if user is allowed to edit this team
            user is a User (from request.user), not a Person
        """
        coordinator = self.get_coordinator()
        return user.is_authenticated() and coordinator and user.username == coordinator.username

    def fill_role(self, role, person):
        """ Used by TeamManager to prefill roles in team """
        if not self.roles:
            self.roles = {'coordinator': [],
                          'committer': [],
                          'reviewer': [],
                          'translator': []}
        self.roles[role].append(person)

    def get_description(self):
        return _(self.description)

    def get_languages(self):
        return self.language_set.all()

    def get_coordinator(self):
        try:
            return self.roles['coordinator'][0]
        except:
            try:
                # The join by role__team__id generates only one query and
                # the same one by role__team=self two queries!
                return Person.objects.get(role__team__id=self.id,
                                          role__role='coordinator')
            except Person.DoesNotExist:
                return None

    def get_members_by_role_exact(self, role):
        """ Return a list of active members """
        try:
            return self.roles[role]
        except:
            members = list(Person.objects.filter(role__team__id=self.id,
                                                 role__role=role,
                                                 role__is_active=True))
            return members

    def get_committers_exact(self):
        return self.get_members_by_role_exact('committer')

    def get_reviewers_exact(self):
        return self.get_members_by_role_exact('reviewer')

    def get_translators_exact(self):
        return self.get_members_by_role_exact('translator')

    def get_members_by_roles(self, roles):
        """Requires a list of roles in argument"""
        try:
            members = []
            for role in roles:
                members += self.roles[role]
        except:
            members = list(Person.objects.filter(role__team__id=self.id,
                                                 role__role__in=roles,
                                                 role__is_active=True))
        return members

    def get_committers(self):
        return self.get_members_by_roles(['coordinator', 'committer'])

    def get_reviewers(self):
        return self.get_members_by_roles(['coordinator', 'committer', 'reviewer'])

    def get_translators(self):
        """Don't use get_members_by_roles to provide an optimization"""
        try:
            members = []
            for role in ['coordinator', 'committer', 'reviewer', 'translator']:
                members += self.roles[role]
        except:
            # Not necessary to filter as for other roles
            members = list(self.members.all())
        return members

    def get_inactive_members(self):
        """ Return the inactive members """
        members = list(Person.objects.filter(role__team__id=self.id,
                                             role__is_active=False))
        return members

    def send_mail_to_coordinator(self, subject, message, messagekw={}):
        """ Send a message to the coordinator, in her language if available
            and if subject and message are lazy strings """
        coordinator = self.get_coordinator()
        if not coordinator or not coordinator.email:
            return
        prev_lang = translation.get_language()
        translation.activate(self.language_set.all()[0].locale)

        message = u"%s\n--\n" % (message % messagekw,)
        message += _(u"This is an automated message sent from %s.") % Site.objects.get_current()
        mail.send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [coordinator.email]
        )
        translation.activate(prev_lang)

class FakeTeam(object):
    """
    This is a class replacing a Team object when a language
    has no team attached.
    """
    fake = 1

    def __init__(self, language):
        self.language = language
        self.description = _("No team for locale %s") % self.language.locale

    @models.permalink
    def get_absolute_url(self):
        return ('teams.views.team', [self.language.locale])

    def can_edit(self, user):
        return False

    def get_description(self):
        return self.language.locale

    def get_languages(self):
        return (self.language,)

    def get_coordinator(self):
        return None


ROLE_CHOICES = (
    ('translator', ugettext_lazy('Translator')),
    ('reviewer', ugettext_lazy('Reviewer')),
    ('committer', ugettext_lazy('Committer')),
    ('coordinator', ugettext_lazy('Coordinator')),
)

class Role(models.Model):
    """
    This is the intermediary class between Person and Team to attribute roles to
    Team members.
    """
    team = models.ForeignKey(Team)
    person = models.ForeignKey(Person)
    role = models.CharField(max_length=15, choices=ROLE_CHOICES,
                            default='translator')
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'role'
        unique_together = ('team', 'person')

    def __unicode__(self):
        return "%s is %s in %s team" % (self.person.name, self.role,
                                        self.team.description)

    @classmethod
    def inactivate_unused_roles(cls):
         """ Inactivate the roles when login older than 180 days  """
         last_login = datetime.now() - timedelta(days=30*6)
         cls.objects.filter(person__last_login__lt=last_login,
                            is_active=True).update(is_active=False)

teams/forms.py
from django import forms
from django.utils.translation import ugettext as _

from common.utils import is_site_admin
from teams.models import Team, Role, ROLE_CHOICES

class EditTeamDetailsForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('webpage_url', 'mailing_list', 'mailing_list_subscribe', 'use_workflow', 'presentation')
        widgets = {
            'webpage_url':  forms.TextInput(attrs={'size': 60}),
            'mailing_list': forms.TextInput(attrs={'size': 60}),
            'mailing_list_subscribe': forms.TextInput(attrs={'size': 60}),
            'presentation': forms.Textarea(attrs={'cols': 60}),
        }

    def __init__(self, user, *args, **kwargs):
        super(EditTeamDetailsForm, self).__init__(*args, **kwargs)
        self.user = user
        if is_site_admin(user):
            # Add coordinatorship dropdown
            all_members = [(r.id, r.person.name) for r in Role.objects.select_related('person').filter(team=self.instance)]
            all_members.insert(0, ('', '-------'))
            try:
                current_coord_pk = Role.objects.filter(team=self.instance, role='coordinator')[0].pk
            except IndexError:
                current_coord_pk = None
            self.fields['coordinatorship'] = forms.ChoiceField(
                label    = _("Coordinator"),
                choices  = all_members,
                required = False,
                initial  = current_coord_pk
            )

    def save(self, *args, **kwargs):
        super(EditTeamDetailsForm, self).save(*args, **kwargs)
        if 'coordinatorship' in self.changed_data and is_site_admin(self.user):
            # Change coordinator
            try:
                # Pass current coordinator as committer
                current_coord = Role.objects.filter(team=self.instance, role='coordinator')[0]
                current_coord.role = 'committer'
                current_coord.save()
            except IndexError:
                pass
            if self.cleaned_data['coordinatorship']:
                new_coord = Role.objects.get(pk=self.cleaned_data['coordinatorship'])
                new_coord.role = 'coordinator'
                new_coord.save()

class EditMemberRoleForm(forms.Form):

    def __init__(self, roles, *args, **kwargs):
        super(EditMemberRoleForm, self).__init__(*args, **kwargs)
        choices = list(filter(lambda x:x[0]!='coordinator', ROLE_CHOICES))
        choices.append(('inactivate', _("Mark as Inactive")))
        choices.append(('remove', _("Remove From Team")))
        for role in roles:
            self.fields[str(role.pk)] = forms.ChoiceField(
                choices=choices,
                label = "<a href='%s'>%s</a>" % (role.person.get_absolute_url(), role.person.name),
                initial=role.role)
        self.fields['form_type'] = forms.CharField(widget=forms.HiddenInput,
                                                   initial=roles[0].role)

    def get_fields(self):
        for key, field in self.fields.items():
            if key not in ('form_type',):
                yield self[key]

templates/teams/team_base.html
{# Variables 'team' and 'language' must be defined prior to calling this template #}
{% load i18n %}

{% with team.get_description as lang %}
<div class="columns">

    <div class="bloc first half">
        <h2>{% trans "Details" %}
            {% if can_edit_details %}
                <a href="{% url team_edit team.name %}">
                    <img src="{{ MEDIA_URL }}img/edit_small.png" alt="Edit"/>
                </a>
            {% endif %}
        </h2>
        
        <dl>
        {% if team.webpage_url %}
          <dt>{% blocktrans %}{{ lang }} Translation Team Page:{% endblocktrans %}</dt>
          <dd><a href="{{ team.webpage_url }}">{{ team.webpage_url }}</a></dd>
        {% endif %}
        </dl>

        <dt>{% trans "Bugzilla:" %}</dt>
        <dd>
            <ul>
                <li><a href="{{ language.bugs_url_enter|safe }}">{% trans "Report Bug in Translation" %}</a></li>
                <li><a href="{{ language.bugs_url_show|safe }}">{% trans "Show Existing Bugs" %}</a></li>
            </ul>
        </dd>

        {% if team.mailing_list %}
        <dt>{% trans "Mailing List:" %}</dt>
        <dd>
            <ul>
                <li><a href="mailto:{{ team.mailing_list }}">{% trans "Send e-mail to the list" %}</a></li>
                {% if team.mailing_list_subscribe %}
                    <li><a href="{{ team.mailing_list_subscribe }}">{% trans "Subscribe" %}</a></li>
                {% endif %}
            </ul>
        </dd>
        {% endif %}
      
    </div>

    <div class="bloc half">
        <h2>{% trans "Coordinator" %}</h2>
        {% if team.get_coordinator %}
          {% with team.get_coordinator as person %}
          {% include "people/person_overview.html" %}
          {% endwith %}
        {% else %}
          <p><em>{% trans "This team has currently no coordinator." %}<br>
             {% blocktrans with link="http://live.gnome.org/TranslationProject/TeamCoordinatorResponsibilities" %}See <a href="{{ link }}">the GTP Wiki</a> for more information about coordinatorship.{% endblocktrans %}</em></p>
        {% endif %}
    </div>

</div>
{% endwith %}

templates/teams/team_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load stats_extras %}
{% load markup %}
{% block extrahead %}
<link rel="alternate" type="application/rss+xml"
      title="{% blocktrans with team.get_description as lang %}Last actions made by the {{ lang }} team of the GNOME Translation Project{% endblocktrans %}"
      href="/rss/teams/{{ team.name }}" />

<script type="text/javascript">
$(document).ready(function() {
        $(".archives").click(function(event) {
            event.preventDefault();
            arch_div = $("#div-rel-archives-"+this.id);
            is_visible = arch_div.is(':visible');
            if (is_visible) {
                arch_div.hide();
                $(this).children('img').attr("src", "{{ MEDIA_URL }}img/closed.png");
            } else {
                if (arch_div.attr("class") == "empty") {
                    // Load the archive stats dynamically
                    arch_div.load("/languages/"+this.id.replace('__','@')+"/rel-archives/");
                    arch_div.attr("class", "loaded");
                }
                arch_div.show();
                $(this).children('img').attr("src", "{{ MEDIA_URL }}img/open.png");
            }
        });
    }
);
</script>
{% endblock %}

{% block title %}{{ team.get_description }}{% endblock %}

{% block content %}
<div class="mainpage">

{% if not team.fake %}

    <h1>{% blocktrans with team.get_description as lang %}{{ lang }} Translation Team{% endblocktrans %}</h1>
    {% if team.presentation %}
        <div>{{ team.presentation|markdown }}</div>
        <hr />
    {% endif %}

    {% with team.get_languages.0 as language %}
        {% include "teams/team_base.html" %}
    {% endwith %}
    
{% else %}

    <h1>{{ team.get_description }}</h1>
    <p><em>{% blocktrans %}There is currently no established team for this language. See <a href="http://live.gnome.org/TranslationProject/StartingATeam">the GTP Wiki</a> to get more information about the process of building a new translation team.{% endblocktrans %}</em></p>

{% endif %}

{% for lang in team.get_languages %}

    <h2>{{ lang.get_name }} <code style="font-weight: normal;">({{ lang.locale }})</code></h2>
    
    {% with 1 as show_all_modules_line %}
        {% with lang.get_release_stats as stats %}
            {% include "languages/language_release_summary.html" %}
        {% endwith %}
    {% endwith %}
    
    <p><strong>{% trans "Plural forms:" %}</strong> {{ lang.get_plurals }}</p>

    <h3><a href="." class="archives" id="{{ lang.locale|escapeat }}"><img src="{{ MEDIA_URL }}img/closed.png" /></a>&nbsp;{% trans "Archives" %}</h3>
    <div id="div-rel-archives-{{ lang.locale|escapeat }}" class="empty" style="display:none;"></div>

{% endfor %}

{% if not team.fake %}
    <h2>{% trans "Team membership" %}</h2>
    
    {% for group in mem_groups %}
        <h3>{{ group.title }}</h3>
        
        {% if group.form %}
        <form action="#" method="POST">
        <ul>
        {% for field in group.form.get_fields %}
          <li>{{ field.label|safe }} {{ field }}</li>
        {% endfor %}
        </ul>
        {{ group.form.form_type }}
        <input type="submit" value="{% trans 'Apply modifications' %}">
        </form>
    {% else %}
      {% if not group.members %}
          <p><em>{{ group.no_member }}</em></p>
      {% else %}
        <ul>
        {% for member in group.members %}
          <li><a href="{{ member.get_absolute_url }}"
              {% if can_edit_team %}
                 title="{% blocktrans with member.last_login|date as last_login %}Last login on {{ last_login }}{% endblocktrans %}"
              {% endif %}>{{ member.name }}</a></li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endif %}
{% endfor %}
{% endif %}

</div>
{% endblock %}

templates/teams/team_edit.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ team.get_description }}{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.growfield2.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#id_presentation").growfield();
});
</script>
{% endblock %}

{% block content %}
<div class="mainpage">
<h1>{% blocktrans with team.get_description as lang %}{{ lang }} Translation Team{% endblocktrans %}</h1>

<form action="#" method="POST">
<table>
  {% if form.coordinatorship %}
  <tr><th>{{ form.coordinatorship.label }}:</th>
      <td>{{ form.coordinatorship.errors}}{{ form.coordinatorship }}</td></tr>
  {% endif %}
  <tr><th>{{ form.webpage_url.label }}:</th>
      <td>{{ form.webpage_url.errors}}{{ form.webpage_url }}</td></tr>
  <tr><th>{{ form.mailing_list.label }}:</th>
      <td>{{ form.mailing_list.errors }}{{ form.mailing_list }}</td></tr>
  <tr><th>{{ form.mailing_list_subscribe.label }}:</th>
      <td>{{ form.mailing_list_subscribe.errors }}{{ form.mailing_list_subscribe }}</td></tr>
  <tr><th></th>
      <td>{{ form.use_workflow }} <label for="id_use_workflow">{% trans "This team is using the Vertimus translation workflow" %}</label>
  <tr><th valign="top"><span class="help">&nbsp;</span><br />{{ form.presentation.label }}:</th>
      <td>{{ form.presentation.label.errors }}
          <span class="help">{% trans "This content may use <a href='http://en.wikipedia.org/wiki/Markdown'>Markdown</a> syntax" %}<br />
          {{ form.presentation }}</td></tr>
  <tr><td colspan="2" align="right"><input type="submit" value="{% trans 'Save' %}"/></td></tr>
</table>
</form>

</div>
{% endblock %}

templates/teams/team_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "GNOME Translation Teams" %}{% endblock %}

{% block content %}
<div class="mainpage">

<h1>{% trans "GNOME Translation Teams" %}</h1>

{% if teams %}
<p>{% trans "Select a team below to see more information about it:" %}</p>

    <ul class="foot">
    {% for team in teams %}
    <li style="font-size: 120%;">
      <a href="{{ team.get_absolute_url }}">{{ team.translated_name }}</a>
      {% if team.webpage_url %}
        &mdash; <a href="{{ team.webpage_url }}">{{ team.webpage_url }}</a>
      {% endif %}
      {% with team.get_coordinator as coordinator %}
      {% if coordinator %}
      <br />
      <span style="font-size: 80%;">
        {% blocktrans with coordinator.get_absolute_url|safe as url and coordinator.name as name %}Coordinated by <a href="{{ url }}">{{ name }}</a>{% endblocktrans %}
      </span>
      {% endif %}
      {% endwith %}
    </li>
    {% endfor %}
    </ul>

    <p class="comment">{% blocktrans %}If anything should be changed on this page, please <a href="{{ bug_url }}">submit a bug report</a>.{% endblocktrans %}</p>

{% else %}
<p>{% trans "There are currently no translation teams in GNOME. :(" %}</p>
{% endif %}

</div>
{% endblock %}