people/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required

from people import views


# Regex order is really important here
urlpatterns = patterns('people.views',
    url(
        r'^detail_change/$',
        login_required(views.PersonEditView.as_view()),
        name = 'person_detail_change'),
    url(
        regex = r'^password_change/$',
        view = 'person_password_change',
        name='person_password_change'),
    url(
        regex = r'^team_join/$',
        view = 'person_team_join',
        name='person_team_join'),
    url(
        regex = r'^team_leave/(?P<team_slug>[\w\-@]+)/$',
        view = 'person_team_leave',
        name='person_team_leave'),
    url(
        r'^(?P<pk>\d+)/$',
        views.PersonDetailView.as_view(),
        name = 'person_detail_id'),
    # Equivalent to the previous, but using username instead of user pk
    url(
        r'^(?P<slug>[\w@\.\-]+)/$',
        views.PersonDetailView.as_view(),
        name = 'person_detail_username'),
)

urlpatterns += patterns('',
    url(r'^$', views.PeopleListView.as_view(), name='people'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(
        regex = r'^$',
        view = 'common.views.index',
        name = 'home'),
    url(
        regex = r'^login/$',
        view = 'common.views.site_login',
        name = 'login'),
    url(
        regex = r'^register/$',
        view = 'common.views.site_register',
        name = 'register'),
    url(
        regex = r'^help/(?P<topic>\w+)/$',
        view = 'common.views.help',
        name = 'help'),
    url(
        regex = r'^register/success$',
        view = TemplateView.as_view(template_name="registration/register_success.html"),
        name = 'register_success'),
    url(
        regex = r'^register/activate/(?P<key>\w+)$',
        view = 'common.views.activate_account',
        name = 'register_activation'),
    url(
        regex = r'^password_reset/$',
        view = 'django.contrib.auth.views.password_reset',
        kwargs = {'template_name':'registration/password_reset_form.html'}),
    url(
        regex = r'^password_reset/done/$',
        view = 'django.contrib.auth.views.password_reset_done',
        kwargs = {'template_name':'registration/password_reset_done.html'}),
    url(
        regex = r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        view = 'django.contrib.auth.views.password_reset_confirm'),
    url(
        regex = r'^reset/done/$',
        view = 'django.contrib.auth.views.password_reset_complete'),
    url(r'^teams/', include('teams.urls')),
    url(r'^people/', include('people.urls')),
    url(# users is the hardcoded url in the contrib.auth User class, making it identical to /people
        r'^users/', include('people.urls')),
    url(r'^languages/', include('languages.urls')),
    url(r'^vertimus/', include('vertimus.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rss/', include('feeds.urls')),
)

urlpatterns += patterns('stats.views',
    url(
        regex = r'^module/(?P<format>(html|json|xml))?/?$',
        view = 'modules',
        name = 'modules'),
    url(
        regex = r'^module/po/(?P<module_name>[\w\-\+]+)/(?P<domain>[\w~\-]+)/(?P<branch_name>[\w\-\.]+)/(?P<filename>.*)$',
        view = 'dynamic_po',
        name = 'dynamic_po'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/$',
        view = 'module'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/edit/branches/$',
        view = 'module_edit_branches'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/branch/(?P<branch_name>[\w\-\.]+)/$',
        view = 'module_branch'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/(?P<potbase>[\w~-]+)/(?P<branch_name>[\w\-\.]+)/(?P<langcode>[\w@]+)/images/$',
        view = 'docimages'),
    url(
        regex = r'^releases/(?P<format>(html|json|xml))?/?$',
        view = 'releases',
        name = 'releases'),
    url(
        regex = r'^releases/(?P<release_name>[\w-]+)/(?P<format>(html|xml))?/?$',
        view = 'release'),
    url(
        regex = r'^releases/compare/(?P<dtype>\w+)/(?P<rels_to_compare>[/\w-]+)/$',
        view = 'compare_by_releases'),
)

if 'django_openid_auth' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^openid/', include('django_openid_auth.urls')),
    )

if settings.STATIC_SERVE:
    urlpatterns += patterns('',
        url(
            regex = r'^media/(?P<path>.*)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.MEDIA_ROOT}),
        url(
            regex = r'^POT/(?P<path>.*)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.POTDIR}),
        url(
            regex = r'^(robots.txt)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.MEDIA_ROOT})
    )

teams/models.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2008 Stéphane Raimbault <stephane.raimbault@gmail.com>.
# Copyright (c) 2009 Claude Paroz <claude@2xlibre.net>
#
# This file is part of Damned Lies.
#
# Damned Lies is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Damned Lies is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Damned Lies; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

from datetime import datetime, timedelta

from django.db import models
from django.core import mail
from django.utils import translation
from django.utils.translation import ugettext_lazy, ugettext as _
from django.conf import settings
from django.contrib.sites.models import Site
from people.models import Person

class TeamManager(models.Manager):

    def all_with_coordinator(self):
        """
        Returns all teams with the coordinator already prefilled. Use that
        function to reduce the size of extracted data and the numbers of objects
        built or use all_with_roles() if you need informations about the other
        roles.
        """
        teams = self.all()
        roles = Role.objects.select_related("person").filter(role='coordinator',
                                                                is_active=True)
        role_dict = {}

        for role in roles:
            # Only one coordinator by team
            role_dict[role.team_id] = role

        for team in teams:
            try:
                role = role_dict[team.id]
                team.roles = {'coordinator': [role.person]}
            except KeyError:
                # Abnormal because a team must have a coordinator but of no
                # consequence
                pass
        return teams

    def all_with_roles(self):
        """
        This method prefills team.coordinator/committer/reviewer/translator to
        reduce subsequent database access.
        """
        teams = self.all()
        roles = Role.objects.select_related("person").filter(is_active=True)
        role_dict = {}

        for role in roles:
            if role.team_id not in role_dict:
                role_dict[role.team_id] = [role]
            else:
                role_dict[role.team_id].append(role)

        for team in teams:
            try:
                for role in role_dict[team.id]:
                    team.fill_role(role.role, role.person)
            except KeyError:
                # Abnormal because a team must have a coordinator but of no
                # consequence
                pass
        return teams


class Team(models.Model):
    """The lang_code is generally used for the name of the team."""

    name = models.CharField(max_length=80)
    description = models.TextField()
    use_workflow = models.BooleanField(default=True)
    presentation = models.TextField(blank=True, verbose_name=_("Presentation"))
    members = models.ManyToManyField(Person, through='Role', related_name='teams')
    webpage_url = models.URLField(null=True, blank=True, verbose_name=_("Web page"))
    mailing_list = models.EmailField(null=True, blank=True, verbose_name=_("Mailing list"))
    mailing_list_subscribe = models.URLField(null=True, blank=True, verbose_name=_("URL to subscribe"))
    objects = TeamManager()

    class Meta:
        db_table = 'team'
        ordering = ('description',)

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self.roles = None

    def __unicode__(self):
        return self.description

    @models.permalink
    def get_absolute_url(self):
        return ('team_slug', [self.name])

    def can_edit(self, user):
        """ Return True if user is allowed to edit this team
            user is a User (from request.user), not a Person
        """
        coordinator = self.get_coordinator()
        return user.is_authenticated() and coordinator and user.username == coordinator.username

    def fill_role(self, role, person):
        """ Used by TeamManager to prefill roles in team """
        if not self.roles:
            self.roles = {'coordinator': [],
                          'committer': [],
                          'reviewer': [],
                          'translator': []}
        self.roles[role].append(person)

    def get_description(self):
        return _(self.description)

    def get_languages(self):
        return self.language_set.all()

    def get_coordinator(self):
        try:
            return self.roles['coordinator'][0]
        except:
            try:
                # The join by role__team__id generates only one query and
                # the same one by role__team=self two queries!
                return Person.objects.get(role__team__id=self.id,
                                          role__role='coordinator')
            except Person.DoesNotExist:
                return None

    def get_members_by_role_exact(self, role):
        """ Return a list of active members """
        try:
            return self.roles[role]
        except:
            members = list(Person.objects.filter(role__team__id=self.id,
                                                 role__role=role,
                                                 role__is_active=True))
            return members

    def get_committers_exact(self):
        return self.get_members_by_role_exact('committer')

    def get_reviewers_exact(self):
        return self.get_members_by_role_exact('reviewer')

    def get_translators_exact(self):
        return self.get_members_by_role_exact('translator')

    def get_members_by_roles(self, roles):
        """Requires a list of roles in argument"""
        try:
            members = []
            for role in roles:
                members += self.roles[role]
        except:
            members = list(Person.objects.filter(role__team__id=self.id,
                                                 role__role__in=roles,
                                                 role__is_active=True))
        return members

    def get_committers(self):
        return self.get_members_by_roles(['coordinator', 'committer'])

    def get_reviewers(self):
        return self.get_members_by_roles(['coordinator', 'committer', 'reviewer'])

    def get_translators(self):
        """Don't use get_members_by_roles to provide an optimization"""
        try:
            members = []
            for role in ['coordinator', 'committer', 'reviewer', 'translator']:
                members += self.roles[role]
        except:
            # Not necessary to filter as for other roles
            members = list(self.members.all())
        return members

    def get_inactive_members(self):
        """ Return the inactive members """
        members = list(Person.objects.filter(role__team__id=self.id,
                                             role__is_active=False))
        return members

    def send_mail_to_coordinator(self, subject, message, messagekw={}):
        """ Send a message to the coordinator, in her language if available
            and if subject and message are lazy strings """
        coordinator = self.get_coordinator()
        if not coordinator or not coordinator.email:
            return
        prev_lang = translation.get_language()
        translation.activate(self.language_set.all()[0].locale)

        message = u"%s\n--\n" % (message % messagekw,)
        message += _(u"This is an automated message sent from %s.") % Site.objects.get_current()
        mail.send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [coordinator.email]
        )
        translation.activate(prev_lang)

class FakeTeam(object):
    """
    This is a class replacing a Team object when a language
    has no team attached.
    """
    fake = 1

    def __init__(self, language):
        self.language = language
        self.description = _("No team for locale %s") % self.language.locale

    @models.permalink
    def get_absolute_url(self):
        return ('teams.views.team', [self.language.locale])

    def can_edit(self, user):
        return False

    def get_description(self):
        return self.language.locale

    def get_languages(self):
        return (self.language,)

    def get_coordinator(self):
        return None


ROLE_CHOICES = (
    ('translator', ugettext_lazy('Translator')),
    ('reviewer', ugettext_lazy('Reviewer')),
    ('committer', ugettext_lazy('Committer')),
    ('coordinator', ugettext_lazy('Coordinator')),
)

class Role(models.Model):
    """
    This is the intermediary class between Person and Team to attribute roles to
    Team members.
    """
    team = models.ForeignKey(Team)
    person = models.ForeignKey(Person)
    role = models.CharField(max_length=15, choices=ROLE_CHOICES,
                            default='translator')
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'role'
        unique_together = ('team', 'person')

    def __unicode__(self):
        return "%s is %s in %s team" % (self.person.name, self.role,
                                        self.team.description)

    @classmethod
    def inactivate_unused_roles(cls):
         """ Inactivate the roles when login older than 180 days  """
         last_login = datetime.now() - timedelta(days=30*6)
         cls.objects.filter(person__last_login__lt=last_login,
                            is_active=True).update(is_active=False)

templates/people/password_change_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Password change' %}{% endblock %}

{% block content %}
<div class="mainpage">

<h2>{% trans 'Password change' %}</h2>

<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<form action="" method="post">
  <table>
  <tr>
    <td colspan="2">{{ form.old_password.errors }}</td>
  <tr>
    <td><label for="id_old_password">{% trans 'Old password:' %}</label></td><td>{{ form.old_password }}</td>
  </tr>
  <tr>
    <td colspan="2">{{ form.new_password1.errors }}</td>
  </tr>
  <tr>
    <td><label for="id_new_password1">{% trans 'New password:' %}</label></td><td>{{ form.new_password1 }}</td>
  </tr>
  <tr>
    <td colspan="2">{{ form.new_password2.errors }}</td>
  </tr>
  <tr>
    <td><label for="id_new_password2">{% trans 'Confirm password:' %}</label></td><td>{{ form.new_password2 }}</td>
  </tr>
  <tr>
    <td></td><td><input type="submit" value="{% trans 'Change my password' %}" /></td>
  </tr>
  </table>
</form>

<div>
{% endblock %}

templates/people/person_base.html
{% extends "base.html" %}
{% load i18n %}
{% load stats_extras %}

{% block title %}{% trans "GNOME Contributor" %}{% endblock %}

{% block content %}
<div class="mainpage">
  {% if on_own_page %}
  <div class="right_actions">
    <ul>
      <li><a href="{% url person_detail_change %}">{% trans "Change your details" %}</a></li>
      <li><a href="{% url person_password_change %}">{% trans "Change your password" %}</a></li>
      <li><a href="{% url person_team_join %}">{% trans "Join a team" %}</a></li>
    </ul>
  </div>
  {% endif %}

  {% include "people/person_overview.html" %}

  {% block subcontent %}
  {% endblock %}
</div>
{% endblock %}

templates/people/person_detail.html
{% extends "people/person_base.html" %}
{% load i18n %}
{% load humanize %}
{% load stats_extras %}

{% block extrahead %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.tablesorter.min.js"></script>
<script type="text/javascript">
$(document).ready(function()
    {
        $("#working_on").tablesorter({
            headers: {
                0: { sorter:'text' }
            },
            sortList: [[0,0]] });
    }
);
</script>
{% endblock %}

{% block subcontent %}
{% if on_own_page %}
  <br clear="right" />
  <div id="language_menu">
    <form action="/i18n/setlang/" method="post">
      {% trans "Site Language:" %}
      <select name="language">
      {% for lang in all_languages %}
        <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %}selected="selected"{% endif %}>{{ lang.1 }}</option>
      {% endfor %}
      </select>
      <br/>
      <input type="submit" value="{% trans "Choose" %}" />
    </form>
  </div>
{% endif %}

{% if person.maintains_modules.all %}
<h2>{% trans "Module maintenance" %}</h2>
<ul>
  {% for module in person.maintains_modules.all %}
  <li><a href="{{ module.get_absolute_url }}">{{ module.get_description }}</a></li>
  {% endfor %}
</ul>
{% endif %}

{% include "people/person_team_membership.html" %}

{% if states %}
<h2>{% trans "Current activity" %}</h2>

<table class="tablesorter" id="working_on">
<thead><tr>
  <th>{% trans "Date" %}</th><th>{% trans "Module" %}</th><th>{% trans "State" %}</th>
</tr></thead>
<tbody>
{% for state in states %}
<tr>
  <td><span style="display: none;">{{ state.updated|date:"c" }}</span>{{ state.updated|naturalday:"DATE_FORMAT" }}</td>
  <td><a href="{{ state.get_absolute_url }}">{{ state.branch.module.get_description }} - {{ state.branch.name }} - {{ state.domain.get_description }} - {{ state.language.get_name }}</a></td>
  <td>{{ state.description }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}

{% endblock %}

templates/people/person_detail_change_form.html
{% extends "people/person_base.html" %}
{% load i18n %}
{% load stats_extras %}

{% block subcontent %}

<h2>{% trans "Change your details" %}</h2>

<form action="" method="POST" class="djform">
  <table>
    {{ form.as_table }}
    <tr>
      <td colspan="2" align="center"><input type="submit" value="{% trans "Save" %}"></td>
    </tr>
  </table>
  <input type="hidden" name="detail_change_form" value="1" />
</form>

{% endblock %}

templates/people/person_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "GNOME Contributors" %}{% endblock %}

{% block content %}
<div class="mainpage">
  <h2>{% trans "GNOME Contributors" %}</h2>

  <p>{% trans "GNOME is being developed by following people:" %}</p>

  {% load list_to_columns %}
  <div style="col3_container">
    {% list_to_columns person_list as columns 3 %}
    {% for l in columns %}
    <div class="col3_column">
      {% for person in l %}
      <div class="person_list">
        {% if person.image %}
        <img src="{{ person.image }}" alt="{{ person.name }}" />
        {% else %}
        <img src="{{ MEDIA_URL }}img/nobody.png" alt="" />
        {% endif %}
        <a class="name" href="{{ person.get_absolute_url }}">{{ person.name }}</a><br />

        {% if person.webpage_url %}
        <a href="{{ person.webpage_url }}">{{ person.webpage_url }}</a><br />
        {% endif %}
      </div>
      {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/people/person_overview.html
{# Variables $person and $printroles must be defined prior to calling this template #}
{# This template is included in person.html, team.html and language-release.html #}

{% load i18n %}

<div class="person_detail">
    <div class="image">
    {% if person.image %}
        <img src="{{ person.image }}" alt="{{ person.name }}" />
    {% else %}
        <img src="{{ MEDIA_URL }}img/nobody.png" alt="" />
    {% endif %}
    </div>
    
    <div class="txt">
        <a class="name" href="{{ person.get_absolute_url }}">{{ person.name }}</a><br />
        
        {% if person.no_spam_email %}
            <a class="email" href="mailto:{{ person.no_spam_email }}">{{ person.no_spam_email }}</a><br />
        {% endif %}

        {% if person.webpage_url %}
            <a class="url" href="{{ person.webpage_url }}">{{ person.webpage_url }}</a><br />
        {% endif %}
        
        {% if person.irc_nick %}
            <span class="label">{% trans "Instant messaging:" %}</span>
            <span class="value">{{ person.irc_nick }}</em> (IRC)</span>
        {% endif %}

        {% if person.no_spam_bugzilla_account %}
        <strong>{% trans "Bugzilla account:" %}</strong> {{ person.no_spam_bugzilla_account }}<br />
        {% endif %}

    </div>
</div>

templates/people/person_password_change_form.html
{% extends "people/person_base.html" %}
{% load i18n %}

{% block subcontent %}

<h2>{% trans 'Password change' %}</h2>

<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<form action="" method="post">
  <table>
  <tr>
    <td colspan="2">{{ form.old_password.errors }}</td>
  <tr>
    <td><label for="id_old_password">{% trans 'Old password:' %}</label></td><td>{{ form.old_password }}</td>
  </tr>
  <tr>
    <td colspan="2">{{ form.new_password1.errors }}</td>
  </tr>
  <tr>
    <td><label for="id_new_password1">{% trans 'New password:' %}</label></td><td>{{ form.new_password1 }}</td>
  </tr>
  <tr>
    <td colspan="2">{{ form.new_password2.errors }}</td>
  </tr>
  <tr>
    <td><label for="id_new_password2">{% trans 'Confirm password:' %}</label></td><td>{{ form.new_password2 }}</td>
  </tr>
  <tr>
    <td></td><td><input type="submit" value="{% trans 'Change my password' %}" /></td>
  </tr>
  </table>
</form>

{% endblock %}

templates/people/person_team_join_form.html
{% extends "people/person_base.html" %}
{% load i18n %}

{% block subcontent %}

{% include "people/person_team_membership.html" %}

<h2>{% trans "Join a new team" %}</h2>

<form action="" method="POST">
  <p><em>{% trans "I would like to join the following team as 'translator':" %}</em><br />
    {{ form.teams }}
    <input type="submit" value="{% trans "Join" %}">
</form>

{% endblock %}

templates/people/person_team_membership.html
{% load i18n %}
{% load stats_extras %}

{% if person.role_set.all %}
<h2>{% trans "Team membership" %}</h2>
<ul>
  {% for role in person.role_set.all %}
  {% with role.get_role_display as role_name %}
  <li>{% blocktrans with role.team|linked_with:role.team.get_description|safe as team_name %}Member of {{ team_name }} team ({{ role_name }}){% endblocktrans %}
      {% if on_own_page %}
      <form class="inline" method="GET" action="{% url person_team_leave role.team.name %}">
        <input type="submit" value="{% trans "Leave" %}"
               onClick="javascript:return confirm('{% trans "Are you sure you want to leave the team?" %}')">
      </form>
      {% endif %}
  </li>
  {% endwith %}
  {% endfor %}
</ul>
{% endif %}