urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(
        regex = r'^$',
        view = 'common.views.index',
        name = 'home'),
    url(
        regex = r'^login/$',
        view = 'common.views.site_login',
        name = 'login'),
    url(
        regex = r'^register/$',
        view = 'common.views.site_register',
        name = 'register'),
    url(
        regex = r'^help/(?P<topic>\w+)/$',
        view = 'common.views.help',
        name = 'help'),
    url(
        regex = r'^register/success$',
        view = TemplateView.as_view(template_name="registration/register_success.html"),
        name = 'register_success'),
    url(
        regex = r'^register/activate/(?P<key>\w+)$',
        view = 'common.views.activate_account',
        name = 'register_activation'),
    url(
        regex = r'^password_reset/$',
        view = 'django.contrib.auth.views.password_reset',
        kwargs = {'template_name':'registration/password_reset_form.html'}),
    url(
        regex = r'^password_reset/done/$',
        view = 'django.contrib.auth.views.password_reset_done',
        kwargs = {'template_name':'registration/password_reset_done.html'}),
    url(
        regex = r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        view = 'django.contrib.auth.views.password_reset_confirm'),
    url(
        regex = r'^reset/done/$',
        view = 'django.contrib.auth.views.password_reset_complete'),
    url(r'^teams/', include('teams.urls')),
    url(r'^people/', include('people.urls')),
    url(# users is the hardcoded url in the contrib.auth User class, making it identical to /people
        r'^users/', include('people.urls')),
    url(r'^languages/', include('languages.urls')),
    url(r'^vertimus/', include('vertimus.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rss/', include('feeds.urls')),
)

urlpatterns += patterns('stats.views',
    url(
        regex = r'^module/(?P<format>(html|json|xml))?/?$',
        view = 'modules',
        name = 'modules'),
    url(
        regex = r'^module/po/(?P<module_name>[\w\-\+]+)/(?P<domain>[\w~\-]+)/(?P<branch_name>[\w\-\.]+)/(?P<filename>.*)$',
        view = 'dynamic_po',
        name = 'dynamic_po'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/$',
        view = 'module'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/edit/branches/$',
        view = 'module_edit_branches'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/branch/(?P<branch_name>[\w\-\.]+)/$',
        view = 'module_branch'),
    url(
        regex = r'^module/(?P<module_name>[\w\-\+]+)/(?P<potbase>[\w~-]+)/(?P<branch_name>[\w\-\.]+)/(?P<langcode>[\w@]+)/images/$',
        view = 'docimages'),
    url(
        regex = r'^releases/(?P<format>(html|json|xml))?/?$',
        view = 'releases',
        name = 'releases'),
    url(
        regex = r'^releases/(?P<release_name>[\w-]+)/(?P<format>(html|xml))?/?$',
        view = 'release'),
    url(
        regex = r'^releases/compare/(?P<dtype>\w+)/(?P<rels_to_compare>[/\w-]+)/$',
        view = 'compare_by_releases'),
)

if 'django_openid_auth' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^openid/', include('django_openid_auth.urls')),
    )

if settings.STATIC_SERVE:
    urlpatterns += patterns('',
        url(
            regex = r'^media/(?P<path>.*)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.MEDIA_ROOT}),
        url(
            regex = r'^POT/(?P<path>.*)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.POTDIR}),
        url(
            regex = r'^(robots.txt)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.MEDIA_ROOT})
    )

vertimus/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('vertimus.views',
    url(
        regex = r'^(?P<stats_id>\d+)/(?P<lang_id>\d+)$',
        view = 'vertimus_by_stats_id',
        name = 'vertimus_by_stats_id'),
    url(
        regex = r'^(?P<branch_id>\d+)/(?P<domain_id>\d+)/(?P<language_id>\d+)',
        view = 'vertimus_by_ids',
        name = 'vertimus_by_ids'),
    url(
        regex = r'^diff/(?P<action_id_1>\d+)/(?P<action_id_2>\d+)/(?P<level>\d+)/$',
        view = 'vertimus_diff',
        name = 'vertimus_diff'),
    url(
        regex = r'^uploads/(?P<module_name>[\w\+\-\.]+)/(?P<branch_name>[\w\-\.]+)/(?P<domain_name>[\w~\-]+)/(?P<locale_name>[\w\-@]+)/latest/$',
        view = 'latest_uploaded_po',
        name = 'latest_uploaded_po'),
    url(
        regex = '^(?P<module_name>[\w\+\-\.]+)/(?P<branch_name>[\w\-\.]+)/(?P<domain_name>[\w~\-]+)/(?P<locale_name>[\w\-@]+)/level(?P<level>\d+)/$',
        view = 'vertimus_by_names',
        name = 'vertimus_archives_by_names'),
    url(
        regex = r'^(?P<module_name>[\w\+\-\.]+)/(?P<branch_name>[\w\-\.]+)/(?P<domain_name>[\w~\-]+)/(?P<locale_name>[\w\-@]+)',
        view = 'vertimus_by_names',
        name = 'vertimus_by_names'),
)

vertimus/models.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2008-2009 Stéphane Raimbault <stephane.raimbault@gmail.com>
# Copyright (c) 2011 Claude Paroz <claude@2xlibre.net>
#
# This file is part of Damned Lies.
#
# Damned Lies is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Damned Lies is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Damned Lies; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import os, sys
import shutil
from datetime import datetime, timedelta

from django.conf import settings
from django.contrib.sites.models import Site
from django.core import mail, urlresolvers
from django.db import models
from django.db.models import Max
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.utils.translation import get_language, activate, ugettext, ugettext_lazy as _

from stats.models import Branch, Domain, Statistics, PoFile
from stats.signals import pot_has_changed
from stats.utils import run_shell_command, is_po_reduced, po_grep
from languages.models import Language
from people.models import Person

from teams.models import Role

#
# States
#

class State(models.Model):
    """State of a module translation"""
    branch = models.ForeignKey(Branch)
    domain = models.ForeignKey(Domain)
    language = models.ForeignKey(Language)
    person = models.ForeignKey(Person, default=None, null=True)

    name = models.SlugField(max_length=20, default='None')
    updated = models.DateTimeField(auto_now=True, auto_now_add=True, editable=False)

    class Meta:
        db_table = 'state'
        verbose_name = 'state'
        unique_together = ('branch', 'domain', 'language')

    def __init__(self, *args, **kwargs):
        super(State, self).__init__(*args, **kwargs)
        if self.name == 'None' and getattr(self.__class__, 'name', 'None') != 'None':
            self.name = self.__class__.name
        self.__class__ = {
            'None'        : StateNone,
            'Translating' : StateTranslating,
            'Translated'  : StateTranslated,
            'Proofreading': StateProofreading,
            'Proofread'   : StateProofread,
            'ToReview'    : StateToReview,
            'ToCommit'    : StateToCommit,
            'Committing'  : StateCommitting,
            'Committed'   : StateCommitted,
        }.get(self.name, State)

    def __unicode__(self):
        return "%s: %s %s (%s - %s)" % (self.name, self.branch.module.name,
            self.branch.name, self.language.name, self.domain.name)

    @models.permalink
    def get_absolute_url(self):
        return ('vertimus_by_ids', [self.branch.id, self.domain.id, self.language.id])

    def change_state(self, state_class, person=None):
        self.name = state_class.name
        self.person = person
        self.__class__ = state_class
        self.save()

    def _get_available_actions(self, person, action_names):
        action_names.append('WC')
        if person.is_committer(self.language.team) and 'IC' not in action_names:
            action_names.extend(('Separator', 'IC', 'AA'))
        return [eval('Action' + action_name)() for action_name in action_names]

    def get_action_sequence_from_level(self, level):
        """Get the sequence corresponding to the requested level.
           The first level is 1."""
        assert level > 0, "Level must be greater than 0"

        query = ActionArchived.objects.filter(state_db=self).values('sequence').distinct().order_by('-sequence')[level-1:level]
        sequence = None
        if len(query) > 0:
            sequence = query[0]['sequence']
        return sequence


class StateNone(State):
    name = 'None'
    description = _('Inactive')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        action_names = []

        if person.is_translator(self.language.team) or person.is_maintainer_of(self.branch.module):
            action_names = ['RT']

        return self._get_available_actions(person, action_names)


class StateTranslating(State):
    name = 'Translating'
    description = _('Translating')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        action_names = []

        if (self.person == person):
            action_names = ['UT', 'UNDO']

        return self._get_available_actions(person, action_names)


class StateTranslated(State):
    name = 'Translated'
    description = _('Translated')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        action_names = []

        if person.is_reviewer(self.language.team):
            action_names.append('RP')
            action_names.append('TR')

        if person.is_translator(self.language.team):
            action_names.append('RT')

        if person.is_committer(self.language.team):
            action_names.append('TC')

        return self._get_available_actions(person, action_names)


class StateProofreading(State):
    name = 'Proofreading'
    description = _('Proofreading')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        action_names = []

        if person.is_reviewer(self.language.team):
            if (self.person == person):
                action_names = ['UP', 'TR', 'TC', 'UNDO']

        return self._get_available_actions(person, action_names)


class StateProofread(State):
    name = 'Proofread'
    # Translators: This is a status, not a verb
    description = _('Proofread')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        if person.is_reviewer(self.language.team):
            action_names = ['TC', 'RP', 'TR']
        else:
            action_names = []
        if not self.branch.is_vcs_readonly() and person.is_committer(self.language.team):
            action_names.insert(1, 'CI')

        return self._get_available_actions(person, action_names)


class StateToReview(State):
    name = 'ToReview'
    description = _('To Review')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        action_names = []
        if person.is_translator(self.language.team):
            action_names.append('RT')

        return self._get_available_actions(person, action_names)


class StateToCommit(State):
    name = 'ToCommit'
    description = _('To Commit')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        if person.is_committer(self.language.team):
            action_names = ['RC', 'TR']
            if not self.branch.is_vcs_readonly():
                action_names.insert(1, 'CI')
        else:
            action_names = []

        return self._get_available_actions(person, action_names)


class StateCommitting(State):
    name = 'Committing'
    description = _('Committing')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        action_names = []

        if person.is_committer(self.language.team):
            if (self.person == person):
                action_names = ['IC', 'TR', 'UNDO']

        return self._get_available_actions(person, action_names)


class StateCommitted(State):
    name = 'Committed'
    description = _('Committed')

    class Meta:
        proxy = True

    def get_available_actions(self, person):
        if person.is_committer(self.language.team):
            action_names = ['AA']
        else:
            action_names = []

        return self._get_available_actions(person, action_names)


#
# Actions
#

ACTION_NAMES = (
    ('WC', _('Write a comment')),
    ('RT', _('Reserve for translation')),
    ('UT', _('Upload the new translation')),
    ('RP', _('Reserve for proofreading')),
    ('UP', _('Upload the proofread translation')),
    # Translators: this means the file is ready to be committed in repository
    ('TC', _('Ready for submission')),
    ('CI', _('Submit to repository')),
    # Translators: this indicates a committer is going to commit the file in the repository
    ('RC', _('Reserve to submit')),
    # Translators: this is used to indicate the file has been committed in the repository
    ('IC', _('Inform of submission')),
    # Translators: regardless of the translation completion, this file need to be reviewed
    ('TR', _('Rework needed')),
    ('AA', _('Archive the actions')),
    ('UNDO', _('Undo the last state change')),
)

def generate_upload_filename(instance, filename):
    if isinstance(instance, ActionArchived):
        return "%s/%s" % (settings.UPLOAD_ARCHIVED_DIR, os.path.basename(filename))
    # Extract the first extension (with the point)
    root, ext = os.path.splitext(filename)
    # Check if a second extension is present
    if os.path.splitext(root)[1] == ".tar":
        ext = ".tar" + ext
    new_filename = "%s-%s-%s-%s-%s%s" % (
        instance.state_db.branch.module.name,
        instance.state_db.branch.name,
        instance.state_db.domain.name,
        instance.state_db.language.locale,
        instance.state_db.id,
        ext)
    return "%s/%s" % (settings.UPLOAD_DIR, new_filename)

class ActionAbstract(models.Model):
    """ Common model for Action and ActionArchived """
    state_db = models.ForeignKey(State)
    person = models.ForeignKey(Person)

    name = models.SlugField(max_length=8)
    created = models.DateTimeField(editable=False)
    comment = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to=generate_upload_filename, blank=True, null=True)

templates/vertimus/vertimus_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}
{% load stats_extras %}

{% block title %}
{% blocktrans with module.get_description as name %}Module Translation: {{ name }}{% endblocktrans %}
{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.growfield2.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#id_comment").growfield();
});
</script>
{% endblock %}

{% block content %}
<div class="mainpage">
{% if action_form.non_field_errors %}
  {{ action_form.non_field_errors }}
{% endif %}

{% with branch.releases.all as releases %}
<div class="release_link">
{% if releases %}
  <p><em>{% trans "Used in release(s):" %}</em><br />
  {% for release in releases %}
    <a href="{% url languages.views.language_release language.locale,release.name,domain.dtype %}">
    {% trans release.description %}
    </a><br/>
  {% endfor %}
{% endif %}
</div>
{% endwith %}

<h1>
<a href="{% url stats.views.module module.name %}">{{ module.get_description }}</a>
» {{ branch.name }} » {{ language.get_name }}
</h1>

<p>{{ domain.get_description }}</p>

<h2 class="plain">
{% trans "State:" %} {{ state.description }}
{% if state.name != 'None' %}
({{ state.updated|date:_("Y-m-d g:i a O") }})
{% endif %}
</h2>

{% if module.get_comment %}
  <p>{{ module.get_comment|safe }}</p>
{% else %}
  {% if not module.has_standard_vcs %}
  <p><em><img src="{{ MEDIA_URL }}img/warn.png" alt="Warning logo" /> {{ non_standard_repo_msg }}</em></p>
  {% endif %}
{% endif %}

<div id="vertimus_stats">
  <div><em><a href="{{ pot_stats.pot_url }}">
      <img src="{{ MEDIA_URL }}img/download.png" alt="{% trans "Download POT file" %}" /></a>
    {{ pot_stats.pot_text }}
  </em></div>
  <div style="display: inline-block">
    <a href="{{ po_url }}"><img src="{{ MEDIA_URL }}img/download.png" alt="{% trans "Download PO file" %}" /></a>
    {% trans "PO file statistics:" %} <br />
    {% trans "Strings:" %} {{ stats|num_stats:"full" }}&nbsp;
    <div class="graph graphinline">
      {{ stats|vis_stats:"full" }}
    </div>
    {% trans "Words:" %} {{ stats|num_word_stats:"full" }}&nbsp;
    <div class="graph graphinline">
      {{ stats|vis_word_stats:"full" }}
    </div>
  </div>
  {% if po_url_reduced %}
  <div style="display: inline-block;">
    <a href="{{ po_url_reduced }}"><img src="{{ MEDIA_URL }}img/download.png" alt="{% trans "Download PO file" %}" /></a>
    {% trans "PO file statistics (reduced):" %}
    <div style="display: inline-block;">
      <span class="help_link"><a href="{% url help 'reduced_po' %}">
        <img src="{{ MEDIA_URL }}img/help.png" alt="help icon">
      </a></span>
    </div>
    <br />
    {% trans "Strings:" %} {{ stats|num_stats:"part" }}&nbsp;
    <div class="graph graphinline">
      {{ stats|vis_stats:"part" }}
    </div>
    {% trans "Words:" %} {{ stats|num_word_stats:"part" }}&nbsp;
    <div class="graph graphinline">
      {{ stats|vis_word_stats:"part" }}
    </div>
  </div>
  {% endif %}
  {% if fig_stats and stats.language %}
  <div class="docimages">
    {% url stats.views.docimages module_name=module.name,potbase=stats.domain.name,branch_name=branch.name,langcode=stats.language.locale as img_url %}
    {% blocktrans with stats=fig_stats|num_stats count total=fig_stats.total %} including <a href="{{ img_url }}">{{ stats }} image</a>{% plural %} including <a href="{{ img_url }}">{{ stats }} images</a>{% endblocktrans %}
  </div>
  {% endif %}
</div>

{% if stats.informations %}
<h4>{% trans "Notices" %}</h4>
<table>
  {% for info in stats.informations %}
  <tr>
    <td valign="top"><img src="{{ info.get_icon }}" alt="{{ info.type }}" /></td>
    <td>{{ info.get_description|safe }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% if other_states %}
<div style="margin-top:0.5em; clear: both;">
  <img src="{{ MEDIA_URL }}img/warn.png" alt="Warning logo" />
  {% trans "On-going activities in same module:" %}
  {% for st in other_states %}
    <a href="{% url vertimus_by_ids st.branch.pk,st.domain.pk,st.language.pk %}">{{ st.branch.name }}</a>
  {% endfor %}
</div>
{% endif %}

{% if language.team.use_workflow %}
<div id="vertimus_actions_title">
  <h2>
    {% if level == 0 %}
      {% trans "Actions" %}
    {% else %}
      {% comment %}Translators: human_level is an ordinal expression ('1st',' 2nd',...)
                   which should be localized in Django itself
      {% endcomment %}
      {% blocktrans with level|ordinal|safe as human_level %}Archived Actions ({{ human_level }} archived series){% endblocktrans %}
      <a href="{% url vertimus_by_names module.name,branch.name,domain.name,language.locale %}">
        {% trans "(Return to current actions)" %}
      </a>
    {% endif %}
    {% if grandparent_level %}
      <a href="{% url vertimus_archives_by_names module.name,branch.name,domain.name,language.locale,grandparent_level %}">
        {% trans "(Previous action history)" %}
      </a>
    {% endif %}
  </h2>
</div>

{% if action_history %}
<div>
  {% for action,files in action_history %}
  <div class="vertimus_action">
    <div class="vertimus_action_head">
      <a name="{{ action.id }}"></a>
      <div class="face_image">
      {% if action.person.image %}<img src="{{ action.person.image }}" alt="face" style="max-height: 50px;"/>
      {% else %}<img src="{{ MEDIA_URL }}img/nobody-16.png" alt="Person"/>
      {% endif %}
      </div>
      <a href="{{ action.person.get_absolute_url }}">{{ action.person.name }}</a>
      , <strong>{{ action.description }}</strong>, {{ action.created|date:_("Y-m-d g:i a O") }}
    </div>
    <div class="vertimus_action_content">
      {% if action.file %}
      <div class="uploaded_file">
        <a href="{{ action.file.url }}" class="download_button">
          {{ action.get_filename }}
        </a>
        <br/>
        {% if action.has_po_file %}
          {% if action.merged_file.url %}
            <a href="{{ action.merged_file.url }}" class="download_button">
              {{ action.merged_file.filename }}
            </a>
            {{ action.merged_file|num_stats:'short' }}<br/>
          {% endif %}
          <div class="right_actions">{% trans "diff with:" %}
            {% for f in files %}
                <a href="{% url vertimus_diff action.id,f.action_id,level %}" title="{{ f.title }}">[{{ forloop.revcounter }}]</a>
            {% endfor %}
          </div>
        {% endif %}
      </div>
      {% endif %}
      {% if action.comment %}
        <p class="vertimus_action_comment">{{ action.comment|urlize|linebreaksbr }}</p>
      {% else %}
        <p><em>{% trans "No comment" %}</em></p>
      {% endif %}
      <br/>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
  <p><em>{% trans "No current actions." %}</em></p>
{% endif %}

{% if level == 0 %}
  <h2>{% trans "New Action" %}</h2>

  {% if action_form %}
  <form enctype="multipart/form-data"
        action="{% url vertimus_by_stats_id stats.id,language.id %}"
        method="POST">
    <table class="djform">
      {% for field in action_form %}
        {{ field|as_tr }}
      {% endfor %}
      <tr>
        <td></td>
        <td><input type="submit" value="{% trans "Submit" %}"></td>
      <tr>
    </table>
  </form>
  {% else %}
  {% blocktrans with language.team.get_description as team_name %}You need to be authenticated and to be member of the {{ team_name }} team.{% endblocktrans %}
  {% endif %}
{% endif %}
{% else %}
  <p><img src="{{ MEDIA_URL }}img/warn.png"/>&nbsp;{% trans "This team is not using the Vertimus translation workflow." %}</p>
{% endif %}

{% endblock %}

templates/vertimus/vertimus_diff.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Diff between po files" %}
{% endblock %}

{% block extrahead %}
  <link rel="stylesheet" href="{{ MEDIA_URL }}css/difflib.css" />
{% endblock %}

{% block content %}
<div class="mainpage">

<h1>{{ state.branch.module.get_description }} - {{ state.branch.name }} - {{ state.domain.get_description }} - {{ state.language.get_name }}</h1>
<p><a href="{% url vertimus_by_names state.branch.module.name,state.branch.name,state.domain.name,state.language.locale %}">{% trans "&lt;- Back to actions" %}</a></p>

{{ diff_content|safe }}

<p><em>{% trans "Note: both files are merged with latest POT file." %}</em></p>
{% endblock %}